version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: anotando
      MYSQL_USER: anotando_user
      MYSQL_PASSWORD: anotando_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: anotando_user
      DB_PASSWORD: anotando_pass
      DB_NAME: anotando
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
